INSERT INTO [dbo].[Atendimento] ([CodigoTipoAtendimento], [SiglaTipoAtendimento],[CodigoAtendente],[CodigoPaciente],[CodigoMedico],[CodigoConvenio],[Descricao],[DataHora]) VALUES

(1,'F',1,2,4,1,'CONSULTA','2022-09-18'),
(2,'F',1,2,4,2,'CONSULTA','2022-09-18'),
(3,'F',1,2,4,3,'CONSULTA','2022-09-20'),
(4,'F',1,2,4,4,'CONSULTA','2022-05-20'),
(1,'F',1,2,4,5,'CONSULTA','2022-05-20'),
(2,'F',1,2,4,6,'CONSULTA','2022-05-20'),
(3,'F',1,2,4,7,'CONSULTA','2022-05-20'),
(4,'F',1,2,4,8,'CONSULTA','2022-11-01'),
(1,'F',1,2,4,9,'CONSULTA','2022-11-05'),
(2,'F',1,2,4,10,'CONSULTA','2022-12-04')
