INSERT INTO [dbo].[Pessoa] ([CodigoTipoPessoa], [SiglaTipoPessoa], [Nome], [CodigoEndereco],[CPF],[Telefone], [Sexo], [Escolaridade],[DataNascimento],[Email], [Cargo],[DataAdmissao],[DataDemissao]) VALUES

(1,'F','Georgi Facello',1,'49001540741','(98)3641-2574','F','SUPERIOR',NULL,'facello.georgi@acme.com',NULL,NULL,NULL),
(2,'F','Bezalel',2,'38050201548','(98)3641-2575','F','SUPERIOR',NULL,'simmel.bezalel@acme.com',NULL,NULL,NULL),
(3,'F','Parto Bamford',3,'45152038868','(98)3641-2576','F','SUPERIOR',NULL,'bamford.parto@acme.com',NULL,NULL,NULL),
(4,'F','Chirstian Koblick',4,'93993062385','(98)3641-2577','F','SUPERIOR',NULL,'koblick.chirstian@acme.com',NULL,NULL,NULL),
(1,'F','Kyoichi',5,'64885131268','(98)3641-2578','F','SUPERIOR',NULL,'maliniak.kyoichi@acme.com',NULL,NULL,NULL),
(2,'F','Anneke Preusig',6,'32097781440','(98)3641-2579','F','SUPERIOR',NULL,'preusig.anneke@acme.com',NULL,NULL,NULL),
(3,'F','Tzvetan',7,'45521773009','(98)3641-2580','F','SUPERIOR',NULL,'zielinski.tzvetan@acme.com',NULL,NULL,NULL),
(4,'F','Saniya Kalloufi',8,'61346916570','(98)3641-2581','F','SUPERIOR',NULL,'kalloufi.saniya@acme.com',NULL,NULL,NULL),
(1,'F','Sumant Peac',9,'97392551134','(98)3641-2582','F','SUPERIOR',NULL,'peac.sumant@acme.com',NULL,NULL,NULL),
(2,'F','Duangkaew Piveteau',1,'67883327357','(98)3641-2583','F','SUPERIOR',NULL,'piveteau.duangkaew@acme.com',NULL,NULL,NULL)
