INSERT INTO [dbo].[evento] ([titulo],[decricao],[data_ida],[data_volta],[id_instituicao],[id_rota_ida],[id_rota_volta],[id_usuario_responsavel]) VALUES 

('Apresentação Romeu e Julieta','Apresentação da obra Romeu e Julieta no Teatro Amazonas','2023-11-15','2023-12-27',1,1,2,1),
('Visita ao Museu','visita ao museu Fortaleza dos Reis Magos','2023-01-28','2023-02-01',5,3,4,50),
('Visita ao Museu','visita ao museu Ver-o-Peso','2023-05-12','2023-05-15',7,5,6,164),
('Visita a cidade de Ouro Preto','visita e passeio pela cidade de Ouro Preto','2023-02-05','2023-02-15',9,7,8,42),
('Visita ao Municicipio de Natividade','visita a cidade preservada de Natividade','2023-09-24','2023-10-05',5,9,10,68),
('Visita a Catedral de Sé','Passeio e visita a Catedral de Sé em São Paulo','2023-09-30','2023-10-10',12,11,12,154),
('Visita a Fortaleza de São José de Macapá','Passeio e visita a antiga Fortaleza de São José de Macapá','2023-11-14','2023-11-20',11,13,14,96)
