INSERT INTO [dbo].[ponto_parada] ([id_ponto_parada],[descricao],[latitude],[longitude],[id_rota]) VALUES
('Teatro Amazonas - Manaus - AM','3° 7' 49,17" S','60° 1' 22,31" W',1),
('Fortaleza dos Reis Magos - Natal - RN','-5.75667 5° 45' 24'' Sul','-35.195 35° 11 42'' Oeste',3),
('Ver-o-Peso - Belém - PA','-1° 27' 4.79" S','-48° 30' 7.79" W',5),
('Ouro Preto - Ouro Preto - MG','-20.3856','-43.5035 20° 23' 8" Sul, 43° 30' 13" Oeste',7),
('Natividade - Natividade - TO','-11.7098','-47.7308 11° 42' 35" Sul, 47° 43' 51" Oeste',9),
('Catedral da Sé - São Paulo - SP','-23.550104 23° 33' 0.3744' S','-46.633953 46° 38' 2.2308' W',11),
('Fortaleza de São José de Macapá - AP','0.031047 / 0° 1' 52' Norte','-51.0492 / 51° 2' 57' Oeste',13)
